name: deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to GitHub Pages
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: public
